const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
const WRONG_PASSWORD = 'WRONG_PASSWORD'
const EMAIL_IS_IN_WRONG = 'EMAIL_IS_IN_WRONG'
const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 ='WORD_LENGTH_MUST_BE_MORE_THAN_8'
const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY'
const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST'
const SOME_THING_WENT_WRONG = 'SOMETHING_WENT_WRONG'
const ID_FORMAT_DOES_NOT_MATCH = 'ID_FORMAT_DOES_NOT_MATCH'
const GATEWAY_TIMEOUT_ERROR = 'GATEWAY_TIMEOUT_ERROR'
const EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';

module.exports = {
    EMAIL_IS_EMPTY,
    PASSWORD_IS_EMPTY,
    WRONG_PASSWORD,
    EMAIL_IS_IN_WRONG_FORMAT,
    EMAIL_IS_IN_WRONG,
    USER_EXISTS_ALREADY,
    USER_DOES_NOT_EXIST,
    SOME_THING_WENT_WRONG,
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8,
    ID_FORMAT_DOES_NOT_MATCH,
    GATEWAY_TIMEOUT_ERROR,

}